defaults:
    - agent: sac

env_type: gym
env: Humanoid-v5

# this needs to be specified manually
experiment: test_exp

num_train_steps: 3e6 # default: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true


seed: 1

ckpt_frequency: 1000
resume_training: false

save_summary_freq: 100


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}